### ISSUE TITLE
Non-PDF version of the bylaws

### ISSUE THREAD

**Issue by benbalter** [presidential-innovation-foundation/presidential-innovation-foundation.github.io#15]
Is there a non-PDF (e.g. Word or markdown) version of the bylaws floating around?

**Comment by benbalter** [comment]
@RobertLRead do you have a Word (or other non-PDF) version of the bylaws, by chance?

**Comment by RobertLRead** [comment]
I have a dock file.  However, our attorneys may have made slight modifications before it was registered---it was a working draft, but I am not sure it is exactly the same.  I will upload it.

**Comment by RobertLRead** [comment]
https://github.com/presidential-innovation-foundation/presidential-innovation-foundation.github.io/blob/master/bylaws/PIFF%20Bylaws%20Final.docx
