### ISSUE TITLE
Bylaws seem to be missing

### ISSUE THREAD

**Issue by RobertLRead** [presidential-innovation-foundation/presidential-innovation-foundation.github.io#25]

**Comment by benbalter** [comment]
See https://github.com/presidential-innovation-foundation/presidential-innovation-foundation.github.io/pull/24 which should resolve the problem (they're there, it's just a bad link).

**Comment by benbalter** [comment]
Also to note once merged #17 should hopefully prevent this going forward.

**Comment by benbalter** [comment]
Fixed via #17 and #29.
