### ISSUE TITLE
Update board page

### ISSUE THREAD

**Issue by jackiekazil** [presidential-innovation-foundation/presidential-innovation-foundation.github.io#49]
http://presidentialinnovation.org/board/

**Comment by jackiekazil** [comment]
@RobertLRead -- how should your title AND Adam's title be listed on the site?

**Comment by jackiekazil** [comment]
@kazilico is going to submit a PR when all the details are gathered in this ticket.

**Comment by RobertLRead** [comment]
I prefer my name in type written as:

Robert L. Read, PhD

![highcontrastheadshot](https://cloud.githubusercontent.com/assets/5296671/13639342/f1fe7592-e5d5-11e5-8817-cf26be56cfd3.jpg)

**Comment by vidyaSpandana** [comment]
![edit_aaf_0898](https://cloud.githubusercontent.com/assets/8659708/13643294/f952f832-e5d4-11e5-99cf-90137d79ae7c.jpg)

I'd like my name written as: Vidya Spandana

And if there is a spot to add a link: www.vidyaspandana.com

Thanks!

**Comment by adamdole** [comment]
![adam_small crop_thumb](https://cloud.githubusercontent.com/assets/4933990/13693216/a268e110-e6fd-11e5-828c-d98d0f305e53.png)

**Comment by adamdole** [comment]
I'd like my name written as: Adam Dole

**Comment by jackiekazil** [comment]
Jackie Kazil

![jackie](https://cloud.githubusercontent.com/assets/166734/13693801/34110800-e70c-11e5-9ba1-01e8be5400cf.jpg)

**Comment by jackiekazil** [comment]
@kazilico

Jackie Kazil, President
Vidya Spandana, Vice President
Adam Dole, Secretary
Robert L. Read, PhD, Treasurer
Ian Kalin, Member-at-large

Use @ianjkalin's last photo. We can update it later if we to.

**Comment by ianjkalin** [comment]
All looks good to me.

**Comment by jackiekazil** [comment]
Fixed in #50
